name: Update Git Submodules

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  SubmoduleSync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
        with:
          submodules: true

      - name: Attempt to update Git Submodules
        run: git pull --recurse-submodules && git submodule update --remote --recursive

      - name: Commit any changes and create a pull request
        run: |
          git add --all .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            # Before pushing changes we update the lockfile and add files again
            yarn
            git add --all .
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_EMAIL}"
            git commit -snam "chore: updated GitHub Submodules at $(date '+%F %H:%M.%S')" || true;
            git push https://${GITHUB_TOKEN}@github.com/sapphiredev/website.git main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.SKYRA_TOKEN }}
          GITHUB_ACTOR: NM-EEA-Y
          GITHUB_EMAIL: contact@skyra.pw
